import { Grad } from "src/app/models/grad.model";

export const GRADOVI: Grad[] = [
  {
    idjezik: "1",
    MBOPS: "70017",
    nOPS: "Aleksandrovac",
    IDNSTJ: "RS216",
  },
  {
    idjezik: "1",
    MBOPS: "70025",
    nOPS: "Aleksinac",
    IDNSTJ: "RS225",
  },
  {
    idjezik: "1",
    MBOPS: "70033",
    nOPS: "Aranđelovac",
    IDNSTJ: "RS218",
  },
  {
    idjezik: "1",
    MBOPS: "70041",
    nOPS: "Arilje",
    IDNSTJ: "RS211",
  },
  {
    idjezik: "1",
    MBOPS: "70050",
    nOPS: "Babušnica",
    IDNSTJ: "RS226",
  },
  {
    idjezik: "1",
    MBOPS: "70068",
    nOPS: "Bajina Bašta",
    IDNSTJ: "RS211",
  },
  {
    idjezik: "1",
    MBOPS: "70076",
    nOPS: "Batočina",
    IDNSTJ: "RS218",
  },
  {
    idjezik: "1",
    MBOPS: "70084",
    nOPS: "Bela Palanka",
    IDNSTJ: "RS226",
  },
  {
    idjezik: "1",
    MBOPS: "70092",
    nOPS: "Barajevo",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70106",
    nOPS: "Voždovac",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70114",
    nOPS: "Vračar",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70122",
    nOPS: "Grocka",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70149",
    nOPS: "Zvezdara",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70157",
    nOPS: "Zemun",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70165",
    nOPS: "Lazarevac",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70173",
    nOPS: "Mladenovac",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70181",
    nOPS: "Novi Beograd",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70190",
    nOPS: "Obrenovac",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70203",
    nOPS: "Palilula (Beograd)",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70211",
    nOPS: "Rakovica",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70220",
    nOPS: "Savski venac",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70238",
    nOPS: "Sopot",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70246",
    nOPS: "Stari grad",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70254",
    nOPS: "Čukarica",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "70262",
    nOPS: "Blace",
    IDNSTJ: "RS229",
  },
  {
    idjezik: "1",
    MBOPS: "70289",
    nOPS: "Bogatić",
    IDNSTJ: "RS213",
  },
  {
    idjezik: "1",
    MBOPS: "70297",
    nOPS: "Bojnik",
    IDNSTJ: "RS224",
  },
  {
    idjezik: "1",
    MBOPS: "70319",
    nOPS: "Boljevac",
    IDNSTJ: "RS223",
  },
  {
    idjezik: "1",
    MBOPS: "70327",
    nOPS: "Bor",
    IDNSTJ: "RS221",
  },
  {
    idjezik: "1",
    MBOPS: "70335",
    nOPS: "Bosilegrad",
    IDNSTJ: "RS228",
  },
  {
    idjezik: "1",
    MBOPS: "70343",
    nOPS: "Brus",
    IDNSTJ: "RS216",
  },
  {
    idjezik: "1",
    MBOPS: "70351",
    nOPS: "Bujanovac",
    IDNSTJ: "RS228",
  },
  {
    idjezik: "1",
    MBOPS: "70360",
    nOPS: "Valjevo",
    IDNSTJ: "RS212",
  },
  {
    idjezik: "1",
    MBOPS: "70378",
    nOPS: "Varvarin",
    IDNSTJ: "RS216",
  },
  {
    idjezik: "1",
    MBOPS: "70386",
    nOPS: "Velika Plana",
    IDNSTJ: "RS227",
  },
  {
    idjezik: "1",
    MBOPS: "70394",
    nOPS: "Veliko Gradište",
    IDNSTJ: "RS222",
  },
  {
    idjezik: "1",
    MBOPS: "70408",
    nOPS: "Vladimirci",
    IDNSTJ: "RS213",
  },
  {
    idjezik: "1",
    MBOPS: "70416",
    nOPS: "Vladičin Han",
    IDNSTJ: "RS228",
  },
  {
    idjezik: "1",
    MBOPS: "70424",
    nOPS: "Vlasotince",
    IDNSTJ: "RS224",
  },
  {
    idjezik: "1",
    MBOPS: "70432",
    nOPS: "Vranje",
    IDNSTJ: "RS228",
  },
  {
    idjezik: "1",
    MBOPS: "70459",
    nOPS: "Vrnjačka Banja",
    IDNSTJ: "RS217",
  },
  {
    idjezik: "1",
    MBOPS: "70467",
    nOPS: "Gadžin Han",
    IDNSTJ: "RS225",
  },
  {
    idjezik: "1",
    MBOPS: "70475",
    nOPS: "Golubac",
    IDNSTJ: "RS222",
  },
  {
    idjezik: "1",
    MBOPS: "70483",
    nOPS: "Gornji Milanovac",
    IDNSTJ: "RS214",
  },
  {
    idjezik: "1",
    MBOPS: "70491",
    nOPS: "Despotovac",
    IDNSTJ: "RS215",
  },
  {
    idjezik: "1",
    MBOPS: "70505",
    nOPS: "Dimitrovgrad",
    IDNSTJ: "RS226",
  },
  {
    idjezik: "1",
    MBOPS: "70513",
    nOPS: "Doljevac",
    IDNSTJ: "RS225",
  },
  {
    idjezik: "1",
    MBOPS: "70521",
    nOPS: "Žabari",
    IDNSTJ: "RS222",
  },
  {
    idjezik: "1",
    MBOPS: "70530",
    nOPS: "Žagubica",
    IDNSTJ: "RS222",
  },
  {
    idjezik: "1",
    MBOPS: "70548",
    nOPS: "Žitorađa",
    IDNSTJ: "RS229",
  },
  {
    idjezik: "1",
    MBOPS: "70556",
    nOPS: "Zaječar",
    IDNSTJ: "RS223",
  },
  {
    idjezik: "1",
    MBOPS: "70564",
    nOPS: "Ivanjica",
    IDNSTJ: "RS214",
  },
  {
    idjezik: "1",
    MBOPS: "70572",
    nOPS: "Kladovo",
    IDNSTJ: "RS221",
  },
  {
    idjezik: "1",
    MBOPS: "70599",
    nOPS: "Knić",
    IDNSTJ: "RS218",
  },
  {
    idjezik: "1",
    MBOPS: "70602",
    nOPS: "Knjaževac",
    IDNSTJ: "RS223",
  },
  {
    idjezik: "1",
    MBOPS: "70629",
    nOPS: "Kosjerić",
    IDNSTJ: "RS211",
  },
  {
    idjezik: "1",
    MBOPS: "70637",
    nOPS: "Koceljeva",
    IDNSTJ: "RS213",
  },
  {
    idjezik: "1",
    MBOPS: "70645",
    nOPS: "Kragujevac",
    IDNSTJ: "RS218",
  },
  {
    idjezik: "1",
    MBOPS: "70653",
    nOPS: "Kraljevo",
    IDNSTJ: "RS217",
  },
  {
    idjezik: "1",
    MBOPS: "70661",
    nOPS: "Krupanj",
    IDNSTJ: "RS213",
  },
  {
    idjezik: "1",
    MBOPS: "70670",
    nOPS: "Kruševac",
    IDNSTJ: "RS216",
  },
  {
    idjezik: "1",
    MBOPS: "70688",
    nOPS: "Kuršumlija",
    IDNSTJ: "RS229",
  },
  {
    idjezik: "1",
    MBOPS: "70696",
    nOPS: "Kučevo",
    IDNSTJ: "RS222",
  },
  {
    idjezik: "1",
    MBOPS: "70700",
    nOPS: "Lajkovac",
    IDNSTJ: "RS212",
  },
  {
    idjezik: "1",
    MBOPS: "70718",
    nOPS: "Lebane",
    IDNSTJ: "RS224",
  },
  {
    idjezik: "1",
    MBOPS: "70726",
    nOPS: "Leskovac ",
    IDNSTJ: "RS224",
  },
  {
    idjezik: "1",
    MBOPS: "70734",
    nOPS: "Loznica",
    IDNSTJ: "RS213",
  },
  {
    idjezik: "1",
    MBOPS: "70742",
    nOPS: "Lučani",
    IDNSTJ: "RS214",
  },
  {
    idjezik: "1",
    MBOPS: "70769",
    nOPS: "Ljig",
    IDNSTJ: "RS212",
  },
  {
    idjezik: "1",
    MBOPS: "70777",
    nOPS: "Ljubovija",
    IDNSTJ: "RS213",
  },
  {
    idjezik: "1",
    MBOPS: "70785",
    nOPS: "Majdanpek",
    IDNSTJ: "RS221",
  },
  {
    idjezik: "1",
    MBOPS: "70793",
    nOPS: "Mali Zvornik",
    IDNSTJ: "RS213",
  },
  {
    idjezik: "1",
    MBOPS: "70807",
    nOPS: "Malo Crniće",
    IDNSTJ: "RS222",
  },
  {
    idjezik: "1",
    MBOPS: "70815",
    nOPS: "Medveđa",
    IDNSTJ: "RS224",
  },
  {
    idjezik: "1",
    MBOPS: "70823",
    nOPS: "Merošina",
    IDNSTJ: "RS225",
  },
  {
    idjezik: "1",
    MBOPS: "70831",
    nOPS: "Mionica",
    IDNSTJ: "RS212",
  },
  {
    idjezik: "1",
    MBOPS: "70840",
    nOPS: "Negotin",
    IDNSTJ: "RS221",
  },
  {
    idjezik: "1",
    MBOPS: "70866",
    nOPS: "Nova Varoš",
    IDNSTJ: "RS211",
  },
  {
    idjezik: "1",
    MBOPS: "70874",
    nOPS: "Novi Pazar",
    IDNSTJ: "RS217",
  },
  {
    idjezik: "1",
    MBOPS: "70882",
    nOPS: "Osečina",
    IDNSTJ: "RS212",
  },
  {
    idjezik: "1",
    MBOPS: "70904",
    nOPS: "Paraćin",
    IDNSTJ: "RS215",
  },
  {
    idjezik: "1",
    MBOPS: "70912",
    nOPS: "Petrovac na Mlavi",
    IDNSTJ: "RS222",
  },
  {
    idjezik: "1",
    MBOPS: "70939",
    nOPS: "Pirot",
    IDNSTJ: "RS226",
  },
  {
    idjezik: "1",
    MBOPS: "70947",
    nOPS: "Požarevac",
    IDNSTJ: "RS222",
  },
  {
    idjezik: "1",
    MBOPS: "70955",
    nOPS: "Požega",
    IDNSTJ: "RS211",
  },
  {
    idjezik: "1",
    MBOPS: "70963",
    nOPS: "Preševo",
    IDNSTJ: "RS228",
  },
  {
    idjezik: "1",
    MBOPS: "70971",
    nOPS: "Priboj",
    IDNSTJ: "RS211",
  },
  {
    idjezik: "1",
    MBOPS: "70980",
    nOPS: "Prijepolje",
    IDNSTJ: "RS211",
  },
  {
    idjezik: "1",
    MBOPS: "70998",
    nOPS: "Prokuplje",
    IDNSTJ: "RS229",
  },
  {
    idjezik: "1",
    MBOPS: "71005",
    nOPS: "Ražanj",
    IDNSTJ: "RS225",
  },
  {
    idjezik: "1",
    MBOPS: "71013",
    nOPS: "Rača",
    IDNSTJ: "RS218",
  },
  {
    idjezik: "1",
    MBOPS: "71021",
    nOPS: "Raška",
    IDNSTJ: "RS217",
  },
  {
    idjezik: "1",
    MBOPS: "71030",
    nOPS: "Rekovac",
    IDNSTJ: "RS215",
  },
  {
    idjezik: "1",
    MBOPS: "71048",
    nOPS: "Jagodina",
    IDNSTJ: "RS215",
  },
  {
    idjezik: "1",
    MBOPS: "71056",
    nOPS: "Svilajnac",
    IDNSTJ: "RS215",
  },
  {
    idjezik: "1",
    MBOPS: "71064",
    nOPS: "Svrljig",
    IDNSTJ: "RS225",
  },
  {
    idjezik: "1",
    MBOPS: "71072",
    nOPS: "Sjenica",
    IDNSTJ: "RS211",
  },
  {
    idjezik: "1",
    MBOPS: "71099",
    nOPS: "Smederevo",
    IDNSTJ: "RS227",
  },
  {
    idjezik: "1",
    MBOPS: "71102",
    nOPS: "Smederevska Palanka",
    IDNSTJ: "RS227",
  },
  {
    idjezik: "1",
    MBOPS: "71129",
    nOPS: "Sokobanja",
    IDNSTJ: "RS223",
  },
  {
    idjezik: "1",
    MBOPS: "71137",
    nOPS: "Surdulica",
    IDNSTJ: "RS228",
  },
  {
    idjezik: "1",
    MBOPS: "71145",
    nOPS: "Užice",
    IDNSTJ: "RS211",
  },
  {
    idjezik: "1",
    MBOPS: "71153",
    nOPS: "Topola",
    IDNSTJ: "RS218",
  },
  {
    idjezik: "1",
    MBOPS: "71161",
    nOPS: "Trgovište",
    IDNSTJ: "RS228",
  },
  {
    idjezik: "1",
    MBOPS: "71170",
    nOPS: "Trstenik",
    IDNSTJ: "RS216",
  },
  {
    idjezik: "1",
    MBOPS: "71188",
    nOPS: "Tutin",
    IDNSTJ: "RS217",
  },
  {
    idjezik: "1",
    MBOPS: "71196",
    nOPS: "Ćićevac",
    IDNSTJ: "RS216",
  },
  {
    idjezik: "1",
    MBOPS: "71200",
    nOPS: "Ćuprija",
    IDNSTJ: "RS215",
  },
  {
    idjezik: "1",
    MBOPS: "71218",
    nOPS: "Ub",
    IDNSTJ: "RS212",
  },
  {
    idjezik: "1",
    MBOPS: "71226",
    nOPS: "Crna Trava",
    IDNSTJ: "RS224",
  },
  {
    idjezik: "1",
    MBOPS: "71234",
    nOPS: "Čajetina",
    IDNSTJ: "RS211",
  },
  {
    idjezik: "1",
    MBOPS: "71242",
    nOPS: "Čačak",
    IDNSTJ: "RS214",
  },
  {
    idjezik: "1",
    MBOPS: "71269",
    nOPS: "Šabac",
    IDNSTJ: "RS213",
  },
  {
    idjezik: "1",
    MBOPS: "71277",
    nOPS: "Lapovo",
    IDNSTJ: "RS218",
  },
  {
    idjezik: "1",
    MBOPS: "71285",
    nOPS: "Niška Banja",
    IDNSTJ: "RS225",
  },
  {
    idjezik: "1",
    MBOPS: "71293",
    nOPS: "Surčin",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "71307",
    nOPS: "Pantelej",
    IDNSTJ: "RS225",
  },
  {
    idjezik: "1",
    MBOPS: "71315",
    nOPS: "Crveni krst",
    IDNSTJ: "RS225",
  },
  {
    idjezik: "1",
    MBOPS: "71323",
    nOPS: "Palilula (Niš)",
    IDNSTJ: "RS225",
  },
  {
    idjezik: "1",
    MBOPS: "71331",
    nOPS: "Medijana",
    IDNSTJ: "RS225",
  },
  {
    idjezik: "1",
    MBOPS: "71340",
    nOPS: "Kostolac",
    IDNSTJ: "RS222",
  },
  {
    idjezik: "1",
    MBOPS: "71358",
    nOPS: "Vranjska Banja",
    IDNSTJ: "RS228",
  },
  {
    idjezik: "1",
    MBOPS: "71366",
    nOPS: "Sevojno",
    IDNSTJ: "RS211",
  },
  {
    idjezik: "1",
    MBOPS: "79014",
    nOPS: "Grad Beograd",
    IDNSTJ: "RS110",
  },
  {
    idjezik: "1",
    MBOPS: "79022",
    nOPS: "Grad Niš",
    IDNSTJ: "RS225",
  },
  {
    idjezik: "1",
    MBOPS: "79049",
    nOPS: "Grad Požarevac",
    IDNSTJ: "RS222",
  },
  {
    idjezik: "1",
    MBOPS: "79057",
    nOPS: "Grad Vranje",
    IDNSTJ: "RS228",
  },
  {
    idjezik: "1",
    MBOPS: "79065",
    nOPS: "Grad Užice",
    IDNSTJ: "RS211",
  },
  {
    idjezik: "1",
    MBOPS: "80012",
    nOPS: "Ada",
    IDNSTJ: "RS124",
  },
  {
    idjezik: "1",
    MBOPS: "80039",
    nOPS: "Alibunar",
    IDNSTJ: "RS122",
  },
  {
    idjezik: "1",
    MBOPS: "80047",
    nOPS: "Apatin",
    IDNSTJ: "RS121",
  },
  {
    idjezik: "1",
    MBOPS: "80055",
    nOPS: "Bač",
    IDNSTJ: "RS123",
  },
  {
    idjezik: "1",
    MBOPS: "80063",
    nOPS: "Bačka Palanka",
    IDNSTJ: "RS123",
  },
  {
    idjezik: "1",
    MBOPS: "80071",
    nOPS: "Bačka Topola",
    IDNSTJ: "RS125",
  },
  {
    idjezik: "1",
    MBOPS: "80080",
    nOPS: "Bački Petrovac",
    IDNSTJ: "RS123",
  },
  {
    idjezik: "1",
    MBOPS: "80098",
    nOPS: "Bela Crkva",
    IDNSTJ: "RS122",
  },
  {
    idjezik: "1",
    MBOPS: "80101",
    nOPS: "Beočin",
    IDNSTJ: "RS123",
  },
  {
    idjezik: "1",
    MBOPS: "80110",
    nOPS: "Bečej",
    IDNSTJ: "RS123",
  },
  {
    idjezik: "1",
    MBOPS: "80128",
    nOPS: "Vršac",
    IDNSTJ: "RS122",
  },
  {
    idjezik: "1",
    MBOPS: "80136",
    nOPS: "Žabalj",
    IDNSTJ: "RS123",
  },
  {
    idjezik: "1",
    MBOPS: "80144",
    nOPS: "Žitište",
    IDNSTJ: "RS126",
  },
  {
    idjezik: "1",
    MBOPS: "80152",
    nOPS: "Zrenjanin",
    IDNSTJ: "RS126",
  },
  {
    idjezik: "1",
    MBOPS: "80179",
    nOPS: "Inđija",
    IDNSTJ: "RS127",
  },
  {
    idjezik: "1",
    MBOPS: "80187",
    nOPS: "Irig",
    IDNSTJ: "RS127",
  },
  {
    idjezik: "1",
    MBOPS: "80195",
    nOPS: "Kanjiža",
    IDNSTJ: "RS124",
  },
  {
    idjezik: "1",
    MBOPS: "80209",
    nOPS: "Kikinda",
    IDNSTJ: "RS124",
  },
  {
    idjezik: "1",
    MBOPS: "80217",
    nOPS: "Kovačica",
    IDNSTJ: "RS122",
  },
  {
    idjezik: "1",
    MBOPS: "80225",
    nOPS: "Kovin",
    IDNSTJ: "RS122",
  },
  {
    idjezik: "1",
    MBOPS: "80233",
    nOPS: "Kula",
    IDNSTJ: "RS121",
  },
  {
    idjezik: "1",
    MBOPS: "80241",
    nOPS: "Mali Iđoš",
    IDNSTJ: "RS125",
  },
  {
    idjezik: "1",
    MBOPS: "80250",
    nOPS: "Nova Crnja",
    IDNSTJ: "RS126",
  },
  {
    idjezik: "1",
    MBOPS: "80268",
    nOPS: "Novi Bečej",
    IDNSTJ: "RS126",
  },
  {
    idjezik: "1",
    MBOPS: "80276",
    nOPS: "Novi Kneževac",
    IDNSTJ: "RS124",
  },
  {
    idjezik: "1",
    MBOPS: "80284",
    nOPS: "Novi Sad ",
    IDNSTJ: "RS123",
  },
  {
    idjezik: "1",
    MBOPS: "80292",
    nOPS: "Opovo",
    IDNSTJ: "RS122",
  },
  {
    idjezik: "1",
    MBOPS: "80306",
    nOPS: "Odžaci",
    IDNSTJ: "RS121",
  },
  {
    idjezik: "1",
    MBOPS: "80314",
    nOPS: "Pančevo",
    IDNSTJ: "RS122",
  },
  {
    idjezik: "1",
    MBOPS: "80322",
    nOPS: "Pećinci",
    IDNSTJ: "RS127",
  },
  {
    idjezik: "1",
    MBOPS: "80349",
    nOPS: "Plandište",
    IDNSTJ: "RS122",
  },
  {
    idjezik: "1",
    MBOPS: "80357",
    nOPS: "Ruma",
    IDNSTJ: "RS127",
  },
  {
    idjezik: "1",
    MBOPS: "80365",
    nOPS: "Senta",
    IDNSTJ: "RS124",
  },
  {
    idjezik: "1",
    MBOPS: "80373",
    nOPS: "Sečanj",
    IDNSTJ: "RS126",
  },
  {
    idjezik: "1",
    MBOPS: "80381",
    nOPS: "Sombor",
    IDNSTJ: "RS121",
  },
  {
    idjezik: "1",
    MBOPS: "80390",
    nOPS: "Srbobran",
    IDNSTJ: "RS123",
  },
  {
    idjezik: "1",
    MBOPS: "80403",
    nOPS: "Sremska Mitrovica",
    IDNSTJ: "RS127",
  },
  {
    idjezik: "1",
    MBOPS: "80411",
    nOPS: "Sremski Karlovci",
    IDNSTJ: "RS123",
  },
  {
    idjezik: "1",
    MBOPS: "80420",
    nOPS: "Stara Pazova",
    IDNSTJ: "RS127",
  },
  {
    idjezik: "1",
    MBOPS: "80438",
    nOPS: "Subotica",
    IDNSTJ: "RS125",
  },
  {
    idjezik: "1",
    MBOPS: "80446",
    nOPS: "Temerin",
    IDNSTJ: "RS123",
  },
  {
    idjezik: "1",
    MBOPS: "80454",
    nOPS: "Titel",
    IDNSTJ: "RS123",
  },
  {
    idjezik: "1",
    MBOPS: "80462",
    nOPS: "Vrbas",
    IDNSTJ: "RS123",
  },
  {
    idjezik: "1",
    MBOPS: "80489",
    nOPS: "Čoka",
    IDNSTJ: "RS124",
  },
  {
    idjezik: "1",
    MBOPS: "80497",
    nOPS: "Šid",
    IDNSTJ: "RS127",
  },
  {
    idjezik: "1",
    MBOPS: "80519",
    nOPS: "Petrovaradin",
    IDNSTJ: "RS123",
  },
  {
    idjezik: "1",
    MBOPS: "89010",
    nOPS: "Grad Novi Sad",
    IDNSTJ: "RS123",
  },
  {
    idjezik: "1",
    MBOPS: "90018",
    nOPS: "Vitina",
    IDNSTJ: "RS233",
  },
  {
    idjezik: "1",
    MBOPS: "90026",
    nOPS: "Vučitrn",
    IDNSTJ: "RS232",
  },
  {
    idjezik: "1",
    MBOPS: "90034",
    nOPS: "Glogovac",
    IDNSTJ: "RS231",
  },
  {
    idjezik: "1",
    MBOPS: "90042",
    nOPS: "Gnjilane",
    IDNSTJ: "RS233",
  },
  {
    idjezik: "1",
    MBOPS: "90069",
    nOPS: "Dečani",
    IDNSTJ: "RS234",
  },
  {
    idjezik: "1",
    MBOPS: "90085",
    nOPS: "Đakovica",
    IDNSTJ: "RS234",
  },
  {
    idjezik: "1",
    MBOPS: "90093",
    nOPS: "Zubin Potok",
    IDNSTJ: "RS232",
  },
  {
    idjezik: "1",
    MBOPS: "90107",
    nOPS: "Istok",
    IDNSTJ: "RS234",
  },
  {
    idjezik: "1",
    MBOPS: "90115",
    nOPS: "Kačanik",
    IDNSTJ: "RS231",
  },
  {
    idjezik: "1",
    MBOPS: "90123",
    nOPS: "Klina",
    IDNSTJ: "RS234",
  },
  {
    idjezik: "1",
    MBOPS: "90131",
    nOPS: "Kosovo Polje",
    IDNSTJ: "RS231",
  },
  {
    idjezik: "1",
    MBOPS: "90140",
    nOPS: "Kosovska Kamenica",
    IDNSTJ: "RS233",
  },
  {
    idjezik: "1",
    MBOPS: "90158",
    nOPS: "Leposavić",
    IDNSTJ: "RS232",
  },
  {
    idjezik: "1",
    MBOPS: "90166",
    nOPS: "Lipljan",
    IDNSTJ: "RS231",
  },
  {
    idjezik: "1",
    MBOPS: "90182",
    nOPS: "Novo Brdo",
    IDNSTJ: "RS233",
  },
  {
    idjezik: "1",
    MBOPS: "90204",
    nOPS: "Obilić",
    IDNSTJ: "RS231",
  },
  {
    idjezik: "1",
    MBOPS: "90212",
    nOPS: "Orahovac",
    IDNSTJ: "RS235",
  },
  {
    idjezik: "1",
    MBOPS: "90239",
    nOPS: "Peć",
    IDNSTJ: "RS234",
  },
  {
    idjezik: "1",
    MBOPS: "90247",
    nOPS: "Podujevo",
    IDNSTJ: "RS231",
  },
  {
    idjezik: "1",
    MBOPS: "90255",
    nOPS: "Prizren",
    IDNSTJ: "RS235",
  },
  {
    idjezik: "1",
    MBOPS: "90263",
    nOPS: "Priština",
    IDNSTJ: "RS231",
  },
  {
    idjezik: "1",
    MBOPS: "90271",
    nOPS: "Srbica",
    IDNSTJ: "RS232",
  },
  {
    idjezik: "1",
    MBOPS: "90280",
    nOPS: "Suva Reka",
    IDNSTJ: "RS235",
  },
  {
    idjezik: "1",
    MBOPS: "90298",
    nOPS: "Kosovska Mitrovica",
    IDNSTJ: "RS232",
  },
  {
    idjezik: "1",
    MBOPS: "90301",
    nOPS: "Uroševac",
    IDNSTJ: "RS231",
  },
  {
    idjezik: "1",
    MBOPS: "90310",
    nOPS: "Štimlje",
    IDNSTJ: "RS231",
  },
  {
    idjezik: "1",
    MBOPS: "90328",
    nOPS: "Štrpce",
    IDNSTJ: "RS231",
  },
  {
    idjezik: "1",
    MBOPS: "90336",
    nOPS: "Gora",
    IDNSTJ: "RS235",
  },
  {
    idjezik: "1",
    MBOPS: "90352",
    nOPS: "Zvečan",
    IDNSTJ: "RS232",
  },
];
